script: "bundle exec rspec spec"
rvm:
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
notifications:
  recipients:
    - JDutil@BurlingtonWebApps.com
